name: Testing stuff

on:
  push:
    branches:
      - builds

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    if: ${{(!contains(join(github.event.head_commit.message)),'#skip')}}"
    steps:
      - uses: actions/checkout@v2
      - name: commits
        env:
          COMMITS: ${{ !contains(join(github.event.head_commit.message),'#skip') }}
        run: echo "$COMMITS"
